config/routes.rb
Rails.application.routes.draw do
  resources :feelings
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'feelings#index'
end

app/models/TagExtensions.rb
module TagExtensions
  def tags_as_string
    tag_names.join(', ')
  end

  def tags_as_string=(string)
    self.tag_names = string.split(/,\s*/)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feeling.rb
class Feeling < ApplicationRecord
  Gutentag::ActiveRecord.call self
  include TagExtensions

  has_rich_text :detail
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :feelings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController
  before_action :set_feeling, only: [:show, :edit, :update, :destroy]

  # GET /feelings
  # GET /feelings.json
  def index
    @feelings = Feeling.order(created_at: "DESC")
    @recommends = Feeling.order(created_at: "ASC")
    @magazines = Feeling.order(created_at: "DESC")
    @pickup = Feeling.order(created_at: "ASC")
    @attention = Feeling.order(created_at: "DESC")
    @popular = Feeling.order(created_at: "ASC")
  end

  # GET /feelings/1
  # GET /feelings/1.json
  def show
    @exist = ActiveStorage::Attachment.find_by(record_id: @feeling.id)
    @image = ActiveStorage::Blob.find(@exist.blob_id) if @exist
    if user_signed_in?
      @userid = current_user.id
    else
      @userid = 0
    end
  end

  # GET /feelings/new
  def new
    @feeling = Feeling.new
  end

  # GET /feelings/1/edit
  def edit; end

  # POST /feelings
  # POST /feelings.json
  def create
    @feeling = Feeling.new(feeling_params)

    respond_to do |format|
      if @feeling.save
        format.html { redirect_to @feeling, notice: 'Feeling was successfully created.' }
        format.json { render :show, status: :created, location: @feeling }
      else
        format.html { render :new }
        format.json { render json: @feeling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feelings/1
  # PATCH/PUT /feelings/1.json
  def update
    respond_to do |format|
      if @feeling.update(feeling_params)
        format.html { redirect_to @feeling, notice: 'Feeling was successfully updated.' }
        format.json { render :show, status: :ok, location: @feeling }
      else
        format.html { render :edit }
        format.json { render json: @feeling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feelings/1
  # DELETE /feelings/1.json
  def destroy
    @feeling.destroy
    respond_to do |format|
      format.html { redirect_to feelings_url, notice: 'Feeling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_feeling
    @feeling = Feeling.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def feeling_params
    params.require(:feeling).permit(:subject, :detail, :organization, :tags_as_string, :response).merge(user_id: current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feelings_helper.rb
module FeelingsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/feelings/_card.html.erb
<div class="uk-margin-bottom">
  <div class="uk-card uk-card-default">
    <div class="uk-card-media-top uk-cover-container">
      <canvas width="334" height="167"></canvas>
      <%= image_tag "/jclubmark.png", class: "uk-cover"%>
    </div>
    <div class="uk-card-body">
      <h3 class="uk-card-title">シーズン最終盤</h3>
      <p>サッカーJリーグもいよいよ最終盤。優勝, 昇格, 残留に向けてチームにメッセージを送ってみましょう！</p>
    </div>
  </div>
</div>
<div class="uk-margin-bottom">
  <div class="uk-card uk-card-default">
    <div class="uk-card-media-top uk-cover-container">
      <canvas width="334" height="167"></canvas>
      <%= image_tag "/mountain.jpg", class: "uk-cover"%>
    </div>
    <div class="uk-card-body">
      <h3 class="uk-card-title">Media Top</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
    </div>
  </div>
</div>
<div class="uk-margin-bottom">
  <div class="uk-card uk-card-default">
    <div class="uk-card-media-top uk-cover-container">
      <canvas width="334" height="167"></canvas>
      <%= image_tag "/mountain.jpg", class: "uk-cover"%>
    </div>
    <div class="uk-card-body">
      <h3 class="uk-card-title">Media Top</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
    </div>
  </div>
</div>
<div class="uk-margin-bottom">
  <div class="uk-card uk-card-default">
    <div class="uk-card-media-top uk-cover-container">
      <canvas width="334" height="167"></canvas>
      <%= image_tag "/mountain.jpg", class: "uk-cover"%>
    </div>
    <div class="uk-card-body">
      <h3 class="uk-card-title">Media Top</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
    </div>
  </div>
</div>

app/views/feelings/_feeling.html.erb
<li>
  <article class="article uk-comment uk-padding uk-visible-toggle" tabindex="-1">
    <%= link_to "", feeling_path(feeling), class: "linkbox" %>
    <header class="uk-comment-header uk-position-relative">
      <div class="uk-grid-medium uk-flex-middle" uk-grid>
        <div class="uk-width-expand">
          <h4 class="uk-comment-title uk-margin-remove">
            <a class="uk-link-reset" href="#"><%=feeling.subject%></a>
          </h4>
          <p class="uk-comment-meta uk-margin-remove-top">
            <a class="uk-link-reset" href="#"><%= time_ago_in_words(feeling.created_at) %></a>
          </p>
        </div>
      </div>
      <div class="uk-position-top-right">
        <% exist = ActiveStorage::Attachment.find_by(record_id: feeling.id) %>
        <% if exist %>
        <%= image_tag ActiveStorage::Blob.find(exist.blob_id), width: "120" %>
        <% end %>
      </div>
    </header>
    <div class="uk-comment-body">
      <p><%=feeling.organization%></p>
    </div>
  </article>
</li>

app/views/feelings/_form.html.erb
<div class="uk-margin-medium uk-margin-remove-bottom">
  <%= form_with(model: feeling, local: true) do |form| %>
  <% if feeling.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(feeling.errors.count, "error") %> prohibited this feeling from being saved:</h2>

    <ul>
      <% feeling.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= form.label "タイトル" %>
    <%= form.text_field :subject, class: "uk-input", placeholder: "title" %>
  </div>

  <div class="field">
    <%= form.label "伝えたい相手" %>
    <%= form.text_field :organization, class: "uk-input", placeholder: "organization or name" %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.rich_text_area :detail, class: "uk-textarea", placeholder: "detail" %>
  </div>

  <div class="field">
    <%= form.label :tags_as_string %>
    <%= form.text_field :tags_as_string, class: "uk-textarea", value: feeling.tags_as_string %>
  </div>

  <div class="field">
    <%= form.label :response %>
    <%= form.text_area :response, class: "uk-textarea", size: "10x5", placeholder: "相手からの返信" %>
  </div>

  <div class="actions">
    <%= form.submit "送信する", class: "uk-button uk-button-default" %>
  </div>
  <% end %>
</div>

app/views/feelings/_header.html.erb
<div class="uk-container uk-container-center">
  <div class="header">
    <%= link_to root_path do %>
    <%= image_tag "/logo1.png", class: "title uk-padding uk-padding-remove-bottom" %>
    <% end %>
    <div class="buttons  uk-margin-medium uk-margin-remove-bottom">
      <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <button class="uk-button uk-button-default">ログアウト</button>
      <% end %>
      <% else %>
      <%= link_to new_user_registration_path do %>
      <button class="uk-button uk-button-default">新規登録</button>
      <% end %>
      <%= link_to new_user_session_path do %>
      <button class="uk-button uk-button-default uk-margin-small-left">ログイン</button>
      <% end %>
      <% end %>
      <% if user_signed_in? %>
      <%= link_to new_feeling_path do %>
      <button class="uk-button uk-button-default uk-margin-small-left">投稿する</button>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/feelings/edit.html.erb
<div class="uk-container uk-container-center uk-margin-medium-bottom">
  <div class="header">
    <%= link_to root_path do %>
    <%= image_tag "/logo1.png", class: "title uk-padding uk-padding-remove-bottom" %>
    <% end %>
  </div>

  <%= render 'form', feeling: @feeling %>

  <%= link_to 'Show', @feeling %> |
  <%= link_to 'Back', feelings_path %>

</div>

app/views/feelings/index.html.erb
<div class="head">
  <%= render "header" %>
  <ul class="uk-padding uk-tab" uk-switcher="connect: .switcher-container">
    <li class="uk-active"><a href="">ホーム</a></li>
    <li><a href="">おすすめ</a></li>
    <li><a href="">マガジン</a></li>
    <li><a href="">ピックアップ</a></li>
    <li><a href="">注目</a></li>
    <li><a href="">人気タグ <span class="uk-margin-small-left" uk-icon="icon: triangle-down"></span></a></li>
  </ul>
</div>
<div class="uk-margin-medium-bottom">
  <ul class="uk-switcher switcher-container uk-margin">
    <li>
      <div class="uk-grid-match uk-grid-small" uk-grid>
        <div class="uk-width-2-3@m">
          <ul class="uk-comment-list uk-list-divider">
            <%= render partial: "feeling", collection: @feelings %>
          </ul>
        </div>
        <div class="uk-width-1-3@m">
          <%= render "card" %>
        </div>
      </div>
    </li>
    <li>
      <div class="uk-grid-match uk-grid-small" uk-grid>
        <div class="uk-width-2-3@m">
          <ul class="uk-comment-list uk-list-divider">
            <%= render partial: "feeling", collection: @recommends %>
          </ul>
        </div>
        <div class="uk-width-1-3@m">
          <%= render "card" %>
        </div>
      </div>
    </li>
    <li>
      <div class="uk-grid-match uk-grid-small" uk-grid>
        <div class="uk-width-2-3@m">
          <ul class="uk-comment-list uk-list-divider">
            <%= render partial: "feeling", collection: @magazines %>
          </ul>
        </div>
        <div class="uk-width-1-3@m">
          <%= render "card" %>
        </div>
      </div>
    </li>
    <li>
      <div class="uk-grid-match uk-grid-small" uk-grid>
        <div class="uk-width-2-3@m">
          <ul class="uk-comment-list uk-list-divider">
            <%= render partial: "feeling", collection: @pickup %>
          </ul>
        </div>
        <div class="uk-width-1-3@m">
          <%= render "card" %>
        </div>
      </div>
    </li>
    <li>
      <div class="uk-grid-match uk-grid-small" uk-grid>
        <div class="uk-width-2-3@m">
          <ul class="uk-comment-list uk-list-divider">
            <%= render partial: "feeling", collection: @attention %>
          </ul>
        </div>
        <div class="uk-width-1-3@m">
          <%= render "card" %>
        </div>
      </div>
    </li>
    <li>
      <div class="uk-grid-match uk-grid-small" uk-grid>
        <div class="uk-width-2-3@m">
          <ul class="uk-comment-list uk-list-divider">
            <%= render partial: "feeling", collection: @popular %>
          </ul>
        </div>
        <div class="uk-width-1-3@m">
          <%= render "card" %>
        </div>
      </div>
    </li>
  </ul>
</div>

app/views/feelings/new.html.erb
<div class="uk-margin-medium-bottom">
  <%= render 'shared/simple-header' %>

  <%= render 'form', feeling: @feeling %>

  <%= link_to 'Back', feelings_path %>
</div>

app/views/feelings/show.html.erb
<%= render "header" %>
<div class="uk-container uk-container-center uk-width-xxlarge uk-margin-top uk-margin-medium-bottom">
  <%# できればアイキャッチを導入したい
  <% if @exist %>
  <%#= image_tag @image %>
  <%# end %>
  <article class="uk-article uk-margin-medium-top">

    <h1 class="uk-article-title"><a class="uk-link-reset" href=""><%= @feeling.subject %></a></h1>

    <p class="uk-article-meta uk-margin-medium-bottom"><%= @feeling.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>

    <% if @feeling.organization.present? %>
    <p class="uk-text-lead">To <%= @feeling.organization %></p>
    <% end %>

    <div class="feeling-detail uk-margin-bottom"><%= @feeling.detail %></div>
    <% @feeling.tag_names.each do |tag| %>
    <%= tag %>
    <% end %>
  </article>
  <%= link_to 'Edit', edit_feeling_path(@feeling) %> |
  <%= link_to 'Back', feelings_path %>
  <% if @feeling.user_id == @userid %>
  | <%= link_to 'Delete', feeling_path(@feeling), method: :delete %>
  <% end %>
  <div class="uk-grid-small uk-child-width-auto uk-margin-top" uk-grid>
    <div>
      <a class="uk-button uk-button-text" href="#">5 Comments</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Convey</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="uk-container uk-container-center">
    <%= yield %>
  </div>
</body>

</html>

app/views/shared/_simple-header.html.erb
<div class="header">
  <%= link_to root_path do %>
  <%= image_tag "/logo1.png", class: "title uk-padding uk-padding-remove-bottom" %>
  <% end %>
</div>